### ISSUE TITLE
Document installation of dj-notebook for VS Code

### ISSUE THREAD

**Issue by pydanny** [pydanny/dj-notebook#3]
- Needs to provide instructions for using dj-notebook with VSCode
- Needs to be a pull request for a new file in the docs folder, not an external article. 
- Must not include any other content except for instructions on how to use dj-notebook with VScode

**Comment by Tejoooo** [comment]
Heyy I m interested to work on this can you assign me to this issue

**Comment by pydanny** [comment]
When you get one of your other tickets completed I will assign you.
