### ISSUE TITLE
Write external web article about dj-notebook

### ISSUE THREAD

**Issue by pydanny** [pydanny/dj-notebook#33]
Once complete open a pull request linking to your original content that you create demonstrating usage of dj-notebook. Blogs, newsletters, dev.to, medium, or other methods apply.

Up to 5 people can submit articles, and I'll assign more than one to the ticket.

- [ ] Article: LINK HERE ADDED BY MAINTAINER
- [ ] Article: LINK HERE ADDED BY MAINTAINER
- [ ] Article: LINK HERE ADDED BY MAINTAINER
- [ ] Article: LINK HERE ADDED BY MAINTAINER
- [ ] Article: LINK HERE ADDED BY MAINTAINER

**Comment by Tejoooo** [comment]
Heyy I m interested to work on this can you assign me to this issue

**Comment by pydanny** [comment]
@Tejoooo Wow! That was fast! I do have a couple change requests for you that will make your article POP.

## 1. DevTo supports code fences. Wrap all your code elements thus:

```python
for i in range(10)
    print(i)
```

## 2. Write about dj-notebook

Your article reads a bit too much like something generated by GitHub CoPilot or ChatGPT. I know this because it doesn't actually show how to install or import dj-notebook. If it helps, here is the usage instructions: https://dj-notebook.readthedocs.io/en/latest/usage.html

**Comment by Tejoooo** [comment]
Ok @pydanny I ll make the necessary changes can u assign me this.

**Comment by Tejoooo** [comment]
@pydanny I have made the changes can u verify it and let me know if i need to do anymore changes
https://dev.to/tejoooo/dj-notebook-3h3a

**Comment by pydanny** [comment]
You literally copied over the docs for this package into an article that directly copies from other content. Please either come up with original content or retract your submission.

**Comment by Tejoooo** [comment]
Ohk I ll come with the modifications

**Comment by pydanny** [comment]
@Tejoooo I'm no longer doing ticket assignments for new developers, but you are welcome to make a submission.
