### ISSUE TITLE
Create optimized 1280×640px dj-notebook logo

### ISSUE THREAD

**Issue by pydanny** [pydanny/dj-notebook#34]
The project could really use a social media logo. Taking submissions for the next 30 days. 

Multiple submissions to be considered and multiple people can be assigned to the ticket, so please don't overwork yourself on this item. I'm not looking for anything fancy.

**Comment by Tejoooo** [comment]
Heyy I m interested to work on this can you assign me to this issue

**Comment by pydanny** [comment]
> Heyy I m interested to work on this can you assign me to this issue

Done! Good luck!

Keep in mind others can work on it too.

**Comment by pydanny** [comment]
@Tejoooo I'm no longer doing ticket assignments for new developers, but you are welcome to make a submission.

**Comment by Tejoooo** [comment]
https://www.canva.com/design/DAFwjEREs8I/SV3tbSfG71vLh3tqPkrplw/edit?utm_content=DAFwjEREs8I&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

@pydanny  can u check this I tried these

**Comment by pydanny** [comment]
Please grant me access so I can take a look. 😄

**Comment by Tejoooo** [comment]
Yeah granted 😅

**Comment by pydanny** [comment]
@Tejoooo Wow! Lovely! I really like the fifth option. 😁 

Can you change the 'DN' abbreviation to 'DJ'? Thanks!

**Comment by Tejoooo** [comment]
Definitely How shld I make the pr

**Comment by pydanny** [comment]
Just add image(s) in .png format to a pull request. If you don't know how to do that I can do it for you and make you a commit/PR co-author.

I can't wait to see item five have the big N replaced with a big J. 😄

**Comment by Tejoooo** [comment]
@pydanny I have added the logo as 6.png if u want any changes that are to be done please let me know

**Comment by pydanny** [comment]
Closed thanks to @Tejoooo's effort on #89
