### ISSUE TITLE
Document installation of dj-notebook for Pycharm

### ISSUE THREAD

**Issue by pydanny** [pydanny/dj-notebook#4]
Reference: https://www.jetbrains.com/help/pycharm/jupyter-notebook-support.html

- Needs to provide instructions for using dj-notebook with pycharm
- Needs to be a pull request for a new file in the docs folder, not an external article. 
- Must not include any other content except for instructions on how to use dj-notebook with pycharm
- Direct copies of existing content will be rejected

**Comment by dikshant182004** [comment]
hii @pydanny can u plz assign this project to me and  can u plz elaborate what type of file u want to get added in your article

**Comment by pydanny** [comment]
I want a markdown file with screen captures. In essence, the same level of quality found in the Jetbrains guide.

**Comment by dikshant182004** [comment]
I just want to confirm that does this markdown file will contain  information regarding pycharm on how to use it.etc
If not, plz tell me the desired topic

**Comment by pydanny** [comment]
Yes, we're need a markdown for with associated images on how to use this library with dj-notebook

**Comment by dikshant182004** [comment]
I have created the markdown file but anyhow it is showing the review required .so plz have a look and plz inform me the changes if u want to make
