### ISSUE TITLE
Add pyproject.toml link to docs

### ISSUE THREAD

**Issue by pydanny** [pydanny/dj-notebook#52]
```toml
[project.urls]
<snip other doc links>
documentation = "https://dj-notebook.readthedocs.io/
```

**Comment by suresh33661** [comment]
Hi can you give the location of docs so I can add it.

**Comment by pydanny** [comment]
@suresh33661 it is in the `pyproject.toml` file in the `[project.urls]` segment.

**Comment by pydanny** [comment]
@specbeck Yes, go for it.

I'm not assigning tickets anymore to people I don't have a history with - people are camping on them without completing them.
