### ISSUE TITLE
Raise warning if not run in DEBUG mode

### ISSUE THREAD

**Issue by pydanny** [pydanny/dj-notebook#75]
**Is your feature request related to a problem? Please describe.**

In our book we mention that the shell and shell_plus should not be run in production. 

**Describe the solution you'd like**

This should use both `warning.warn` and send a red message to the shell.

**Comment by skyforest** [comment]
Raise a warning or actually disallow the use of shell / shell-plus if production?

**Comment by pydanny** [comment]
Raise a warning. Everyone's use case is different. 

I believe You and I typically deal with public facing services, but I know of intranets where this having notebook access to org-serving projects would be very useful.  😄

**Comment by pydanny** [comment]
Done and merged thanks to the awesome that is @skyforest 😄
