### ISSUE TITLE
Fix code smell issue in configuration

### ISSUE THREAD

**Issue by pydanny** [pydanny/dj-notebook#88]
**Describe the bug**

Code shouldn't know there might be tests. However, to get tests to work I [hacked this into place](https://github.com/pydanny/dj-notebook/blob/main/src/dj_notebook/__init__.py#L20-L38).

**Expected behavior**

There should be no check for tests in regular code.

**Comment by RalphHuber** [comment]
Mind if I look at this? I started looking at it at pycon and have some ideas

**Comment by pydanny** [comment]
Yes! Go ahead!

**Comment by geoffbeier** [comment]
Interesting, and related: `test_warning_when_debug_false()` depends on this smell as well; it only works if the fake config from the special case in `activate()` has been loaded first.

@RalphHuber I started looking at #7 and this smell spread into my patch idea for that one really quickly, so I wound up yak shaving before I thought too hard about it.

I have a quick idea that will get rid of the special case in `activate()` as well as making sure `test_thing` and `test_warning_when_debug_false` are truly independent of each other, and I will follow this comment with a very small PR.

I invite both you and @pydanny to please just close my PR and let me know it if it looks like it interferes with some more ambitious ideas you've been bouncing around for longer than the timebox I gave my yak shaving exercise.

**Comment by pydanny** [comment]
Closed in #120
